"""Add Report model for PDF reports

Revision ID: 0f452f437c97
Revises: c318be17d646
Create Date: 2026-01-15 11:54:33.560274

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f452f437c97'
down_revision = 'c318be17d646'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_number', sa.String(length=50), nullable=False),
    sa.Column('study_instance_uid', sa.String(length=255), nullable=False),
    sa.Column('patient_id', sa.String(length=20), nullable=True),
    sa.Column('patient_name', sa.String(length=255), nullable=True),
    sa.Column('report_type', sa.String(length=50), nullable=True),
    sa.Column('report_date', sa.Date(), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('generation_task_id', sa.String(length=100), nullable=True),
    sa.Column('image_count', sa.Integer(), nullable=True),
    sa.Column('generated_by', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['generated_by'], ['admins.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reports_patient_id'), ['patient_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reports_report_date'), ['report_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_reports_report_number'), ['report_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_reports_study_instance_uid'), ['study_instance_uid'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reports_study_instance_uid'))
        batch_op.drop_index(batch_op.f('ix_reports_report_number'))
        batch_op.drop_index(batch_op.f('ix_reports_report_date'))
        batch_op.drop_index(batch_op.f('ix_reports_patient_id'))

    op.drop_table('reports')
    # ### end Alembic commands ###
