"""Add password reset token fields

Revision ID: 30cccf5b0ba5
Revises: mt001
Create Date: 2026-02-03 07:04:32.792251

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30cccf5b0ba5'
down_revision = 'mt001'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reset_token', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('reset_token_expiry', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_admins_clinic_id'), ['clinic_id'], unique=False)

    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_appointments_clinic_id'), ['clinic_id'], unique=False)

    with op.batch_alter_table('clinics', schema=None) as batch_op:
        batch_op.drop_column('max_patients')
        batch_op.drop_column('license_type')
        batch_op.drop_column('license_expiry')

    with op.batch_alter_table('dicom_images', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dicom_images_clinic_id'), ['clinic_id'], unique=False)

    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_patients_clinic_id'), ['clinic_id'], unique=False)

    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reports_clinic_id'), ['clinic_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reports_clinic_id'))

    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_patients_clinic_id'))

    with op.batch_alter_table('dicom_images', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dicom_images_clinic_id'))

    with op.batch_alter_table('clinics', schema=None) as batch_op:
        batch_op.add_column(sa.Column('license_expiry', sa.DATE(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('license_type', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('max_patients', sa.INTEGER(), autoincrement=False, nullable=True))

    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_appointments_clinic_id'))

    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_admins_clinic_id'))
        batch_op.drop_column('reset_token_expiry')
        batch_op.drop_column('reset_token')

    # ### end Alembic commands ###
