"""add report lifecycle and accession_number

Revision ID: 43d5c280afec
Revises: d49105459477
Create Date: 2026-02-06 06:13:01.544123

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43d5c280afec'
down_revision = 'd49105459477'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    
    # Check which columns already exist
    result = conn.execute(sa.text("""
        SELECT column_name 
        FROM information_schema.columns 
        WHERE table_name='reports'
    """))
    existing_columns = [row[0] for row in result.fetchall()]
    
    with op.batch_alter_table('reports', schema=None) as batch_op:
        # Only add columns if they don't exist
        if 'accession_number' not in existing_columns:
            batch_op.add_column(sa.Column('accession_number', sa.String(length=50), nullable=False))
        if 'appointment_id' not in existing_columns:
            batch_op.add_column(sa.Column('appointment_id', sa.Integer(), nullable=True))
        if 'report_state' not in existing_columns:
            batch_op.add_column(sa.Column('report_state', sa.String(length=20), nullable=False))
        if 'validated_at' not in existing_columns:
            batch_op.add_column(sa.Column('validated_at', sa.DateTime(), nullable=True))
        if 'validated_by' not in existing_columns:
            batch_op.add_column(sa.Column('validated_by', sa.Integer(), nullable=True))
        
        # Alter file_path only if needed (check current nullable status)
        result = conn.execute(sa.text("""
            SELECT is_nullable 
            FROM information_schema.columns 
            WHERE table_name='reports' AND column_name='file_path'
        """))
        file_path_nullable = result.fetchone()
        if file_path_nullable and file_path_nullable[0] == 'NO':
            batch_op.alter_column('file_path',
                   existing_type=sa.VARCHAR(length=500),
                   nullable=True)
        
        # Check existing indexes
        result = conn.execute(sa.text("""
            SELECT indexname 
            FROM pg_indexes 
            WHERE tablename='reports'
        """))
        existing_indexes = [row[0] for row in result.fetchall()]
        
        if 'ix_reports_accession_number' not in existing_indexes and 'accession_number' in existing_columns:
            batch_op.create_index(batch_op.f('ix_reports_accession_number'), ['accession_number'], unique=False)
        if 'ix_reports_appointment_id' not in existing_indexes and 'appointment_id' in existing_columns:
            batch_op.create_index(batch_op.f('ix_reports_appointment_id'), ['appointment_id'], unique=False)
        
        # Check existing foreign keys
        result = conn.execute(sa.text("""
            SELECT conname 
            FROM pg_constraint 
            WHERE conrelid = 'reports'::regclass AND contype = 'f'
        """))
        existing_fks = [row[0] for row in result.fetchall()]
        
        # Only create foreign keys if columns exist and FKs don't exist
        if 'appointment_id' in existing_columns:
            # Check if FK to appointments already exists
            result = conn.execute(sa.text("""
                SELECT conname 
                FROM pg_constraint 
                WHERE conrelid = 'reports'::regclass 
                AND contype = 'f' 
                AND confrelid = 'appointments'::regclass
                AND conkey::text LIKE '%appointment_id%'
            """))
            if result.fetchone() is None:
                batch_op.create_foreign_key(None, 'appointments', ['appointment_id'], ['id'])
        
        if 'validated_by' in existing_columns:
            # Check if FK to admins already exists
            result = conn.execute(sa.text("""
                SELECT conname 
                FROM pg_constraint 
                WHERE conrelid = 'reports'::regclass 
                AND contype = 'f' 
                AND confrelid = 'admins'::regclass
                AND conkey::text LIKE '%validated_by%'
            """))
            if result.fetchone() is None:
                batch_op.create_foreign_key(None, 'admins', ['validated_by'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_reports_appointment_id'))
        batch_op.drop_index(batch_op.f('ix_reports_accession_number'))
        batch_op.alter_column('file_path',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
        batch_op.drop_column('validated_by')
        batch_op.drop_column('validated_at')
        batch_op.drop_column('report_state')
        batch_op.drop_column('appointment_id')
        batch_op.drop_column('accession_number')

    # ### end Alembic commands ###
