"""add report lifecycle and accession_number

Revision ID: 43d5c280afec
Revises: d49105459477
Create Date: 2026-02-06 06:13:01.544123

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43d5c280afec'
down_revision = 'd49105459477'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('accession_number', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('appointment_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('report_state', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('validated_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('validated_by', sa.Integer(), nullable=True))
        batch_op.alter_column('file_path',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_reports_accession_number'), ['accession_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_reports_appointment_id'), ['appointment_id'], unique=False)
        batch_op.create_foreign_key(None, 'appointments', ['appointment_id'], ['id'])
        batch_op.create_foreign_key(None, 'admins', ['validated_by'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_reports_appointment_id'))
        batch_op.drop_index(batch_op.f('ix_reports_accession_number'))
        batch_op.alter_column('file_path',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
        batch_op.drop_column('validated_by')
        batch_op.drop_column('validated_at')
        batch_op.drop_column('report_state')
        batch_op.drop_column('appointment_id')
        batch_op.drop_column('accession_number')

    # ### end Alembic commands ###
