"""Add is_super_admin field to admins table

Revision ID: 48ef69e1ed0f
Revises: c3456d7ca944
Create Date: 2026-01-08 18:45:25.755462

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48ef69e1ed0f'
down_revision = 'c3456d7ca944'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Step 1: Add column as nullable first
    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_super_admin', sa.Boolean(), nullable=True))
    
    # Step 2: Set default value for existing rows (False)
    op.execute("UPDATE admins SET is_super_admin = FALSE WHERE is_super_admin IS NULL")
    
    # Step 3: Set admin user to super admin
    op.execute("UPDATE admins SET is_super_admin = TRUE WHERE username = 'admin'")
    
    # Step 4: Make column NOT NULL
    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.alter_column('is_super_admin', nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.drop_column('is_super_admin')

    # ### end Alembic commands ###
