"""Add items_json to prescriptions

Revision ID: 51c270f32e2b
Revises: b8bc87a36e3a
Create Date: 2026-02-06 12:57:47.104356

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51c270f32e2b'
down_revision = 'b8bc87a36e3a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prescriptions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('items_json', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prescriptions', schema=None) as batch_op:
        batch_op.drop_column('items_json')

    # ### end Alembic commands ###
