"""expand patient details

Revision ID: 622593b6227d
Revises: 30cccf5b0ba5
Create Date: 2026-02-05 10:30:08.513612

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '622593b6227d'
down_revision = '30cccf5b0ba5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('maiden_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('social_security_number', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('secondary_phone', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('other_phone', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('occupation', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('smoker', sa.String(length=3), nullable=True))
        batch_op.add_column(sa.Column('cigarettes_per_day', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('family_history', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('medical_history', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('gynecological_history', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('allergies', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('delivery_location', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('legacy_number', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.drop_column('legacy_number')
        batch_op.drop_column('delivery_location')
        batch_op.drop_column('allergies')
        batch_op.drop_column('gynecological_history')
        batch_op.drop_column('medical_history')
        batch_op.drop_column('family_history')
        batch_op.drop_column('cigarettes_per_day')
        batch_op.drop_column('smoker')
        batch_op.drop_column('occupation')
        batch_op.drop_column('other_phone')
        batch_op.drop_column('secondary_phone')
        batch_op.drop_column('social_security_number')
        batch_op.drop_column('maiden_name')

    # ### end Alembic commands ###
