"""pdf_spec: accession_number MWL fields report_lifecycle audit_log soft_delete

Revision ID: 6961835db9dc
Revises: 622593b6227d
Create Date: 2026-02-06 10:56:03.344844

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6961835db9dc'
down_revision = '622593b6227d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=True),
    sa.Column('action', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['admins.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_entity_id'), ['entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_entity_type'), ['entity_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('accession_number', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('requested_procedure_id', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('scheduled_procedure_step_id', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_appointments_accession_number'), ['accession_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_appointments_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_appointments_requested_procedure_id'), ['requested_procedure_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_appointments_scheduled_procedure_step_id'), ['scheduled_procedure_step_id'], unique=False)

    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_patients_deleted_at'), ['deleted_at'], unique=False)

    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lifecycle_state', sa.String(length=20), nullable=False, server_default='draft'))
        batch_op.add_column(sa.Column('validated_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('validated_by', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('accession_number', sa.String(length=64), nullable=True))
        batch_op.create_index(batch_op.f('ix_reports_accession_number'), ['accession_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_reports_lifecycle_state'), ['lifecycle_state'], unique=False)
        batch_op.create_index(batch_op.f('ix_reports_validated_by'), ['validated_by'], unique=False)
        batch_op.create_foreign_key(None, 'admins', ['validated_by'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_reports_validated_by'))
        batch_op.drop_index(batch_op.f('ix_reports_lifecycle_state'))
        batch_op.drop_index(batch_op.f('ix_reports_accession_number'))
        batch_op.drop_column('accession_number')
        batch_op.drop_column('validated_by')
        batch_op.drop_column('validated_at')
        batch_op.drop_column('lifecycle_state')

    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_patients_deleted_at'))
        batch_op.drop_column('deleted_at')

    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_appointments_scheduled_procedure_step_id'))
        batch_op.drop_index(batch_op.f('ix_appointments_requested_procedure_id'))
        batch_op.drop_index(batch_op.f('ix_appointments_deleted_at'))
        batch_op.drop_index(batch_op.f('ix_appointments_accession_number'))
        batch_op.drop_column('deleted_at')
        batch_op.drop_column('scheduled_procedure_step_id')
        batch_op.drop_column('requested_procedure_id')
        batch_op.drop_column('accession_number')

    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_entity_type'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_entity_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_action'))

    op.drop_table('audit_logs')
    # ### end Alembic commands ###
