"""test

Revision ID: 6f94f3e1f18c
Revises: 8d2ca02eea5d
Create Date: 2026-01-06 15:36:36.168951

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f94f3e1f18c'
down_revision = '8d2ca02eea5d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('patients_clinic_id_key'), type_='unique')
        batch_op.drop_column('clinic_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('clinic_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.create_unique_constraint(batch_op.f('patients_clinic_id_key'), ['clinic_id'], postgresql_nulls_not_distinct=False)

    # ### end Alembic commands ###
