"""Add DICOM models

Revision ID: 7691b4a8bcfb
Revises: 48ef69e1ed0f
Create Date: 2026-01-12 11:30:48.604222

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7691b4a8bcfb'
down_revision = '48ef69e1ed0f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dicom_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sop_instance_uid', sa.String(length=255), nullable=False),
    sa.Column('study_instance_uid', sa.String(length=255), nullable=True),
    sa.Column('series_instance_uid', sa.String(length=255), nullable=True),
    sa.Column('patient_id', sa.String(length=20), nullable=True),
    sa.Column('patient_name', sa.String(length=255), nullable=True),
    sa.Column('patient_birth_date', sa.Date(), nullable=True),
    sa.Column('patient_sex', sa.String(length=10), nullable=True),
    sa.Column('accession_number', sa.String(length=50), nullable=True),
    sa.Column('study_date', sa.Date(), nullable=True),
    sa.Column('study_time', sa.String(length=20), nullable=True),
    sa.Column('study_description', sa.String(length=255), nullable=True),
    sa.Column('series_number', sa.Integer(), nullable=True),
    sa.Column('series_description', sa.String(length=255), nullable=True),
    sa.Column('modality', sa.String(length=10), nullable=True),
    sa.Column('instance_number', sa.Integer(), nullable=True),
    sa.Column('body_part_examined', sa.String(length=100), nullable=True),
    sa.Column('manufacturer', sa.String(length=100), nullable=True),
    sa.Column('manufacturer_model_name', sa.String(length=100), nullable=True),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('thumbnail_path', sa.String(length=500), nullable=True),
    sa.Column('dicom_metadata', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('dicom_images', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dicom_images_accession_number'), ['accession_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_dicom_images_modality'), ['modality'], unique=False)
        batch_op.create_index(batch_op.f('ix_dicom_images_patient_id'), ['patient_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_dicom_images_series_instance_uid'), ['series_instance_uid'], unique=False)
        batch_op.create_index(batch_op.f('ix_dicom_images_sop_instance_uid'), ['sop_instance_uid'], unique=True)
        batch_op.create_index(batch_op.f('ix_dicom_images_study_date'), ['study_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_dicom_images_study_instance_uid'), ['study_instance_uid'], unique=False)

    op.create_table('dicom_studies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('study_instance_uid', sa.String(length=255), nullable=False),
    sa.Column('patient_id', sa.String(length=20), nullable=False),
    sa.Column('study_date', sa.Date(), nullable=False),
    sa.Column('study_time', sa.String(length=20), nullable=True),
    sa.Column('study_description', sa.String(length=255), nullable=True),
    sa.Column('accession_number', sa.String(length=50), nullable=True),
    sa.Column('referring_physician', sa.String(length=255), nullable=True),
    sa.Column('institution_name', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('dicom_studies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dicom_studies_accession_number'), ['accession_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_dicom_studies_patient_id'), ['patient_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_dicom_studies_study_date'), ['study_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_dicom_studies_study_instance_uid'), ['study_instance_uid'], unique=True)

    op.create_table('dicom_measurements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dicom_image_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.String(length=20), nullable=True),
    sa.Column('study_instance_uid', sa.String(length=255), nullable=True),
    sa.Column('measurement_type', sa.String(length=100), nullable=True),
    sa.Column('measurement_value', sa.String(length=255), nullable=True),
    sa.Column('measurement_data', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['dicom_image_id'], ['dicom_images.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('dicom_measurements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dicom_measurements_patient_id'), ['patient_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_dicom_measurements_study_instance_uid'), ['study_instance_uid'], unique=False)

    op.create_table('dicom_series',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('series_instance_uid', sa.String(length=255), nullable=False),
    sa.Column('study_id', sa.Integer(), nullable=False),
    sa.Column('modality', sa.String(length=10), nullable=False),
    sa.Column('series_number', sa.Integer(), nullable=True),
    sa.Column('series_description', sa.String(length=255), nullable=True),
    sa.Column('body_part_examined', sa.String(length=100), nullable=True),
    sa.Column('series_date', sa.Date(), nullable=True),
    sa.Column('series_time', sa.String(length=20), nullable=True),
    sa.Column('manufacturer', sa.String(length=100), nullable=True),
    sa.Column('manufacturer_model_name', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['study_id'], ['dicom_studies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('dicom_series', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dicom_series_modality'), ['modality'], unique=False)
        batch_op.create_index(batch_op.f('ix_dicom_series_series_instance_uid'), ['series_instance_uid'], unique=True)
        batch_op.create_index(batch_op.f('ix_dicom_series_study_id'), ['study_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dicom_series', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dicom_series_study_id'))
        batch_op.drop_index(batch_op.f('ix_dicom_series_series_instance_uid'))
        batch_op.drop_index(batch_op.f('ix_dicom_series_modality'))

    op.drop_table('dicom_series')
    with op.batch_alter_table('dicom_measurements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dicom_measurements_study_instance_uid'))
        batch_op.drop_index(batch_op.f('ix_dicom_measurements_patient_id'))

    op.drop_table('dicom_measurements')
    with op.batch_alter_table('dicom_studies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dicom_studies_study_instance_uid'))
        batch_op.drop_index(batch_op.f('ix_dicom_studies_study_date'))
        batch_op.drop_index(batch_op.f('ix_dicom_studies_patient_id'))
        batch_op.drop_index(batch_op.f('ix_dicom_studies_accession_number'))

    op.drop_table('dicom_studies')
    with op.batch_alter_table('dicom_images', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dicom_images_study_instance_uid'))
        batch_op.drop_index(batch_op.f('ix_dicom_images_study_date'))
        batch_op.drop_index(batch_op.f('ix_dicom_images_sop_instance_uid'))
        batch_op.drop_index(batch_op.f('ix_dicom_images_series_instance_uid'))
        batch_op.drop_index(batch_op.f('ix_dicom_images_patient_id'))
        batch_op.drop_index(batch_op.f('ix_dicom_images_modality'))
        batch_op.drop_index(batch_op.f('ix_dicom_images_accession_number'))

    op.drop_table('dicom_images')
    # ### end Alembic commands ###
