"""Consolidate DICOM into single table - remove study and series tables

Revision ID: c318be17d646
Revises: c7e3b585e143
Create Date: 2026-01-12 12:02:39.382942

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c318be17d646'
down_revision = 'c7e3b585e143'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # First, update dicom_images table - drop foreign key and column
    with op.batch_alter_table('dicom_images', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dicom_images_series_id'))
        batch_op.drop_constraint(batch_op.f('dicom_images_series_id_fkey'), type_='foreignkey')
        batch_op.drop_column('series_id')
        batch_op.add_column(sa.Column('referring_physician', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('institution_name', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('series_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('series_time', sa.String(length=20), nullable=True))
        batch_op.alter_column('study_instance_uid',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('series_instance_uid',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('study_date',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.alter_column('modality',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
    
    # Now drop dicom_series (no longer has dependencies)
    with op.batch_alter_table('dicom_series', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dicom_series_modality'))
        batch_op.drop_index(batch_op.f('ix_dicom_series_series_instance_uid'))
        batch_op.drop_index(batch_op.f('ix_dicom_series_study_id'))

    op.drop_table('dicom_series')
    
    # Then drop dicom_studies
    with op.batch_alter_table('dicom_studies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dicom_studies_accession_number'))
        batch_op.drop_index(batch_op.f('ix_dicom_studies_patient_id'))
        batch_op.drop_index(batch_op.f('ix_dicom_studies_study_date'))
        batch_op.drop_index(batch_op.f('ix_dicom_studies_study_instance_uid'))

    op.drop_table('dicom_studies')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dicom_images', schema=None) as batch_op:
        batch_op.add_column(sa.Column('series_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('dicom_images_series_id_fkey'), 'dicom_series', ['series_id'], ['id'])
        batch_op.create_index(batch_op.f('ix_dicom_images_series_id'), ['series_id'], unique=False)
        batch_op.alter_column('modality',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
        batch_op.alter_column('study_date',
               existing_type=sa.DATE(),
               nullable=True)
        batch_op.alter_column('series_instance_uid',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('study_instance_uid',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.drop_column('series_time')
        batch_op.drop_column('series_date')
        batch_op.drop_column('institution_name')
        batch_op.drop_column('referring_physician')

    op.create_table('dicom_series',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('series_instance_uid', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('study_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('modality', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('series_number', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('series_description', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('body_part_examined', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('series_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('series_time', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('manufacturer', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('manufacturer_model_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['study_id'], ['dicom_studies.id'], name=op.f('dicom_series_study_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('dicom_series_pkey'))
    )
    with op.batch_alter_table('dicom_series', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dicom_series_study_id'), ['study_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_dicom_series_series_instance_uid'), ['series_instance_uid'], unique=True)
        batch_op.create_index(batch_op.f('ix_dicom_series_modality'), ['modality'], unique=False)

    op.create_table('dicom_studies',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('study_instance_uid', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('patient_id', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('study_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('study_time', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('study_description', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('accession_number', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('referring_physician', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('institution_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('dicom_studies_patient_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('dicom_studies_pkey'))
    )
    with op.batch_alter_table('dicom_studies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dicom_studies_study_instance_uid'), ['study_instance_uid'], unique=True)
        batch_op.create_index(batch_op.f('ix_dicom_studies_study_date'), ['study_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_dicom_studies_patient_id'), ['patient_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_dicom_studies_accession_number'), ['accession_number'], unique=False)

    # ### end Alembic commands ###
