"""Add series_id foreign key to dicom_images

Revision ID: c7e3b585e143
Revises: 7691b4a8bcfb
Create Date: 2026-01-12 11:54:15.149860

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7e3b585e143'
down_revision = '7691b4a8bcfb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dicom_images', schema=None) as batch_op:
        batch_op.add_column(sa.Column('series_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_dicom_images_series_id'), ['series_id'], unique=False)
        batch_op.create_foreign_key(None, 'dicom_series', ['series_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dicom_images', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_dicom_images_series_id'))
        batch_op.drop_column('series_id')

    # ### end Alembic commands ###
