"""add_accession_number_to_appointment

Revision ID: d49105459477
Revises: 622593b6227d
Create Date: 2026-02-06 06:10:04.721227

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd49105459477'
down_revision = '622593b6227d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('accession_number', sa.String(length=50), nullable=True))
        batch_op.create_index(batch_op.f('ix_appointments_accession_number'), ['accession_number'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_appointments_accession_number'))
        batch_op.drop_column('accession_number')

    # ### end Alembic commands ###
