"""add_accession_number_to_appointment

Revision ID: d49105459477
Revises: 622593b6227d
Create Date: 2026-02-06 06:10:04.721227

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd49105459477'
down_revision = '622593b6227d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Check if column already exists (may have been added manually or by another migration)
    conn = op.get_bind()
    result = conn.execute(sa.text("""
        SELECT column_name 
        FROM information_schema.columns 
        WHERE table_name='appointments' AND column_name='accession_number'
    """))
    column_exists = result.fetchone() is not None
    
    if not column_exists:
        with op.batch_alter_table('appointments', schema=None) as batch_op:
            batch_op.add_column(sa.Column('accession_number', sa.String(length=50), nullable=True))
    
    # Check if index already exists before creating
    result = conn.execute(sa.text("""
        SELECT indexname 
        FROM pg_indexes 
        WHERE tablename='appointments' AND indexname='ix_appointments_accession_number'
    """))
    index_exists = result.fetchone() is not None
    
    if not index_exists:
        with op.batch_alter_table('appointments', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_appointments_accession_number'), ['accession_number'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_appointments_accession_number'))
        batch_op.drop_column('accession_number')

    # ### end Alembic commands ###
