"""Add visit_id and appointment_id to DicomImage

Revision ID: dda99c309d17
Revises: f1a2b3c4d5e6
Create Date: 2026-02-13 11:03:29.394712

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dda99c309d17'
down_revision = 'f1a2b3c4d5e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('report_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clinic_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('template_type', sa.String(length=20), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('fields', sa.Text(), nullable=False),
    sa.Column('required_fields', sa.Text(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('report_templates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_report_templates_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_report_templates_clinic_id'), ['clinic_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_report_templates_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_report_templates_language'), ['language'], unique=False)
        batch_op.create_index(batch_op.f('ix_report_templates_template_type'), ['template_type'], unique=False)

    with op.batch_alter_table('dicom_images', schema=None) as batch_op:
        batch_op.add_column(sa.Column('visit_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('appointment_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_dicom_images_appointment_id'), ['appointment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_dicom_images_visit_id'), ['visit_id'], unique=False)
        batch_op.create_foreign_key(None, 'appointments', ['appointment_id'], ['id'])
        batch_op.create_foreign_key(None, 'visits', ['visit_id'], ['id'])

    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('visit_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('template_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('template_data', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('language', sa.String(length=10), nullable=True))
        batch_op.alter_column('file_path',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_reports_template_id'), ['template_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reports_visit_id'), ['visit_id'], unique=True)
        batch_op.create_foreign_key(None, 'visits', ['visit_id'], ['id'])
        batch_op.create_foreign_key(None, 'report_templates', ['template_id'], ['id'])
        batch_op.drop_column('report_state')
        batch_op.drop_column('appointment_id')

    with op.batch_alter_table('visits', schema=None) as batch_op:
        batch_op.alter_column('visit_status',
               existing_type=sa.VARCHAR(length=30),
               nullable=True,
               existing_server_default=sa.text("'scheduled'::character varying"))
        batch_op.alter_column('modality',
               existing_type=sa.VARCHAR(length=10),
               nullable=True,
               existing_server_default=sa.text("'US'::character varying"))
        batch_op.drop_index(batch_op.f('ix_visits_visit_status'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visits', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_visits_visit_status'), ['visit_status'], unique=False)
        batch_op.alter_column('modality',
               existing_type=sa.VARCHAR(length=10),
               nullable=False,
               existing_server_default=sa.text("'US'::character varying"))
        batch_op.alter_column('visit_status',
               existing_type=sa.VARCHAR(length=30),
               nullable=False,
               existing_server_default=sa.text("'scheduled'::character varying"))

    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('appointment_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('report_state', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_reports_visit_id'))
        batch_op.drop_index(batch_op.f('ix_reports_template_id'))
        batch_op.alter_column('file_path',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
        batch_op.drop_column('language')
        batch_op.drop_column('template_data')
        batch_op.drop_column('template_id')
        batch_op.drop_column('visit_id')

    with op.batch_alter_table('dicom_images', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_dicom_images_visit_id'))
        batch_op.drop_index(batch_op.f('ix_dicom_images_appointment_id'))
        batch_op.drop_column('appointment_id')
        batch_op.drop_column('visit_id')

    with op.batch_alter_table('report_templates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_report_templates_template_type'))
        batch_op.drop_index(batch_op.f('ix_report_templates_language'))
        batch_op.drop_index(batch_op.f('ix_report_templates_code'))
        batch_op.drop_index(batch_op.f('ix_report_templates_clinic_id'))
        batch_op.drop_index(batch_op.f('ix_report_templates_category'))

    op.drop_table('report_templates')
    # ### end Alembic commands ###
