"""Add clinic_id to DicomMeasurement and Prescription

Revision ID: f78e091dd096
Revises: dda99c309d17
Create Date: 2026-02-16 17:00:04.042385

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f78e091dd096'
down_revision = 'dda99c309d17'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dicom_measurements', schema=None) as batch_op:
        batch_op.add_column(sa.Column('clinic_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_dicom_measurements_clinic_id'), ['clinic_id'], unique=False)
        batch_op.create_foreign_key(None, 'clinics', ['clinic_id'], ['id'])

    with op.batch_alter_table('prescriptions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('clinic_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_prescriptions_clinic_id'), ['clinic_id'], unique=False)
        batch_op.create_foreign_key(None, 'clinics', ['clinic_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prescriptions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_prescriptions_clinic_id'))
        batch_op.drop_column('clinic_id')

    with op.batch_alter_table('dicom_measurements', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_dicom_measurements_clinic_id'))
        batch_op.drop_column('clinic_id')

    # ### end Alembic commands ###
