from app.extensions import db
from .base import TimestampMixin
from datetime import date
import re


class Patient(db.Model, TimestampMixin):
    __tablename__ = 'patients'

    # Patient ID (string like PAT001, PAT002...) - now generated by backend
    id = db.Column(db.String(20), primary_key=True)
    clinic_id = db.Column(db.Integer, db.ForeignKey('clinics.id'), nullable=True, index=True)

    # Personal
    title = db.Column(db.String(10))  # Mr, Ms, Mrs
    first_name = db.Column(db.String(100), nullable=False)
    last_name = db.Column(db.String(100), nullable=False)
    maiden_name = db.Column(db.String(100))  # Additional surname field
    gender = db.Column(db.String(20))
    birth_date = db.Column(db.Date)  # DOB
    phone = db.Column(db.String(20), unique=True, nullable=False)
    email = db.Column(db.String(120), unique=True, nullable=True)

    
    identity_number = db.Column(db.String(50))
    social_security_number = db.Column(db.String(50))
    secondary_phone = db.Column(db.String(20))
    other_phone = db.Column(db.String(20))
    occupation = db.Column(db.String(100))
    height = db.Column(db.Float)  # cm
    weight = db.Column(db.Float)   # kg
    blood_group = db.Column(db.String(5))
    smoker = db.Column(db.String(3))  # Yes/No
    cigarettes_per_day = db.Column(db.Integer)
    family_history = db.Column(db.Text)
    medical_history = db.Column(db.Text)  # medical / surgical
    gynecological_history = db.Column(db.Text)
    allergies = db.Column(db.Text)
    notes = db.Column(db.Text)
    primary_doctor = db.Column(db.String(100))
    delivery_location = db.Column(db.String(100))
    legacy_number = db.Column(db.String(50))
    new_patient = db.Column(db.Boolean, default=True)  # True = New, False = Existing

    # Demographics (free-form or JSON for future extensions)
    demographics = db.Column(db.Text)

    # Soft delete (no hard deletion of medical data - PDF spec §9)
    deleted_at = db.Column(db.DateTime, nullable=True, index=True)

    # Relationships
    appointments = db.relationship('Appointment', backref='patient', lazy='dynamic')
    
    def __repr__(self):
        return f"<Patient {self.first_name} {self.last_name} ({self.id})>"

    @classmethod
    def generate_new_id(cls):
        """
        Generate next patient ID like PAT001, PAT002, PAT003...
        Always uses PAT prefix with 3-digit zero-padded number.
        Finds the highest existing number to avoid gaps.
        """
        # Get all patient IDs that start with PAT
        all_patients = cls.query.filter(cls.id.like('PAT%')).all()
        
        if not all_patients:
            return "PAT001"
        
        # Extract all numeric suffixes and find the maximum
        max_number = 0
        for patient in all_patients:
            match = re.search(r'PAT(\d+)$', patient.id)
            if match:
                try:
                    num = int(match.group(1))
                    max_number = max(max_number, num)
                except ValueError:
                    continue
        
        # Generate next ID with 3-digit padding
        next_number = max_number + 1
        return f"PAT{next_number:03d}"