from app.extensions import db
from .base import TimestampMixin
from datetime import date
import re


class Patient(db.Model, TimestampMixin):
    __tablename__ = 'patients'

    # Patient ID (string like PAT001, PAT002...) - now generated by backend
    id = db.Column(db.String(20), primary_key=True)
    clinic_id = db.Column(db.Integer, db.ForeignKey('clinics.id'), nullable=True, index=True)

    # Personal
    title = db.Column(db.String(10))  # Mr, Ms, Mrs
    first_name = db.Column(db.String(100), nullable=False)
    last_name = db.Column(db.String(100), nullable=False)
    maiden_name = db.Column(db.String(100))  # Additional surname field
    gender = db.Column(db.String(20))
    birth_date = db.Column(db.Date)  # DOB
    phone = db.Column(db.String(20), unique=True, nullable=False)
    email = db.Column(db.String(120), unique=True, nullable=True)

    
    identity_number = db.Column(db.String(50))
    social_security_number = db.Column(db.String(50))
    secondary_phone = db.Column(db.String(20))
    other_phone = db.Column(db.String(20))
    occupation = db.Column(db.String(100))
    height = db.Column(db.Float)  # cm
    weight = db.Column(db.Float)   # kg
    blood_group = db.Column(db.String(5))
    smoker = db.Column(db.String(3))  # Yes/No
    cigarettes_per_day = db.Column(db.Integer)
    family_history = db.Column(db.Text)
    medical_history = db.Column(db.Text)  # medical / surgical
    gynecological_history = db.Column(db.Text)
    allergies = db.Column(db.Text)
    notes = db.Column(db.Text)
    primary_doctor = db.Column(db.String(100))
    delivery_location = db.Column(db.String(100))
    legacy_number = db.Column(db.String(50))
    new_patient = db.Column(db.Boolean, default=True)  # True = New, False = Existing

    # Demographics (free-form or JSON for future extensions)
    demographics = db.Column(db.Text)

    # Relationships
    appointments = db.relationship('Appointment', backref='patient', lazy='dynamic')
    
    def __repr__(self):
        return f"<Patient {self.first_name} {self.last_name} ({self.id})>"

    @classmethod
    def generate_new_id(cls):
        """
        Generate next patient ID like PAT001, PAT002...
        Uses the numeric suffix of the latest existing ID.
        """
        # Get the most recently created patient
        last_patient = cls.query.order_by(cls.created_at.desc()).first()
        if not last_patient or not last_patient.id:
            return "PAT001"

        # Extract trailing digits from last ID
        match = re.search(r'(\d+)$', last_patient.id)
        if not match:
            # Fallback if existing IDs don't match pattern
            return "PAT001"

        number = int(match.group(1)) + 1
        prefix = last_patient.id[:-len(match.group(1))] or "PAT"
        return f"{prefix}{number:03d}"